baseURL = "https://clever-hawking-c1249c.netlify.com/"
title = "Alternative Act"
theme = "a-a-theme"
enableRobotsTXT = true
languageCode = "ja"
hasCJKLanguage = true
DefaultContentLanguage = "ja"
MetaDataFormat = "yaml"
SectionPagesMenu = "main"
Paginate = 10

[[menu.main]]
    name = "About"
    title = "About"
    weight = 90
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Artists"
    title = "Artists"
    weight = 100
    identifier = "artists"
    url = "/artists/"
[[menu.main]]
    name = "Ticket"
    title = "Ticket"
    weight = 110
    identifier = "ticket"
    url = "/ticket/"
[[menu.main]]
    name = "Contact"
    title = "Contact"
    weight = 120
    identifier = "contact"
    url = "/contact/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
  favicon = "images/favicon.ico"
  description = "Alternative Act 1.0 Tech Performance Fes. 技術と芸術を繋ぎなおす、新しい世代の表現者たちによる二日間のパフォーマンス・イベント。"
  facebook = ""
  twitter = "https://twitter.com/AlternativeAct_"
  instagram = ""
  youtube = ""
  # background_color_class = "bg-blue"
  featured_image = 'images/logo/blueback.jpeg'
  recent_posts_number = 8
  body_classes = "helvetica system-sans-serif"
