backend:
  name: git-gateway

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"

collections: # A list of collections the CMS should be able to edit
  - name: "artists" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Artists" # Used in the UI, ie.: "New Post"
    folder: "content/artists" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "アーティスト名", name: "title", widget: "string"}
      - {label: "アーティスト名（En）", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - file: "content/artists/_index.md"
        label: "Artists"
        name: "artists_index"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Description", name: "description", widget: "string", required: false}
      - file: "content/about/_index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Description", name: "description", widget: "string", required: false}
      - file: "content/about/_index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Description", name: "description", widget: "string", required: false}
      - file: "content/contact/_index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Description", name: "description", widget: "string", required: false}
      - file: "content/tickets/_index.md"
        label: "Tickets"
        name: "tickets"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Description", name: "description", widget: "string", required: false}
